version: '3.7'
services:
  db:
    image: postgres:10.1-alpine
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:6.5.3
  #   ports:
  #     - '5601:5601'
  web:
    build: .
    command: bin/rails s -p 3000 -b '0.0.0.0'
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
#     links:
#       - elasticsearch
#   elasticsearch:
#       hostname: elasticsearch
#       restart: always
#       image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.3
#       environment:
#         - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#       networks:
#         - internal_network
#       ports:
#         - "9200:9200"
#         - "9300:9300"
#       volumes:
#         - elasticsearch:/usr/share/elasticsearch/data
# networks:
#   external_network:
#   internal_network:
#     internal: true
# volumes:
#   elasticsearch:
#     driver: local