version: '3'
services:
  unitedideas-db:
    image: postgres:10.2
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=unitedideas
      - POSTGRES_DB=unitedideas_development
    volumes:
      - data-volume:/var/lib/postgresql
  unitedideas-migrate:
    build:
      context: .
      dockerfile: Dockerfile.development
    depends_on:
      - unitedideas-db
    environment:
      - PASSENGER_APP_ENV=development
    command: ["./wait-for-postgres.sh", "unitedideas-db", "bin/rails", "db:migrate"]
  unitedideas:
    build:
      context: .
      dockerfile: Dockerfile.development
    depends_on:
      - unitedideas-db
      - unitedideas-migrate
    ports:
      - "80:80"
    environment:
      - PASSENGER_APP_ENV=development
      - RAILS_LOG_TO_STDOUT=true
    volumes:
      - .:/home/app/webapp
volumes:
  data-volume:
